sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jgqiDmVx+C7Jw8lNK/MeyXx3s3KfyQdsZvwuGVl7fa8z2aHEMsSS7/rWSc9rjl1Heyc8yfTl928yk5t2z0ytrp4oWSCLhw7jW2EUVT8pe9F8PhRN9dhiLHHs5oB/0vNHrYZTN3Og5ZNGGAGG5mOyLMqirNpYqV+h5VyFTRQC+oUgh+DcxQFcs65+ZNVbvedw2RzjLH7E+OThH7Jm9NAfIvdqeZ7LTObrxpL2ad8ZyvjwPSQeczDNnF5PUl7zP6T3z5Qd3lvym3dc2sJL+qL7qKs8jM7KfpGAs/BIXxDXxJPXRMuSEDaq5KV7IMnXMs+3BZThAjebUWpzpzN8TOqXxUBQMxTJJ+yPX5m7YuE1NZIHWuqLs/QPLfXNUPZo4HkchYE/y1AP9P7Vrl8m1K5CJfHAHLmRLdsmaTd90JflpAK2fC36rjt+bnDy/SmJlp7qC2ke90h5BgbVq6K57tW41h2sKqR8XXV8lPsink3uUCTqtt9oYPJjdc5ZZasoltnSSaWhUvvbj4F0IdtFBvdFeGFkA8G7g0jbjycrAo+xEwMkI2fTln7gxw8Fyv1ZPXpSFM9G4mOwB5jUxrY7BT7Bvvz4CnADAH5bZk4A/ASHYozVhkaNCnEMSBOMFkePea6r9DpMLsnwk/nmG/EyEnnmEpmb9jCGP0WeLHoR+2B67Hk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Romance-of-Elaine--13-Sequel-to--Exploits-of-Elaine-_5094
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy